<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<NoWarn>NU1701</NoWarn>
		<!-- 忽略 NU1701 警告 -->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
		<PackageReference Include="ScottPlot.WPF" Version="5.1.59" />
		<PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
	</ItemGroup>

</Project>