<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<NoWarn>NU1701</NoWarn>
		<!-- 忽略 NU1701 警告 -->
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="fonts\msyh.ttc" />
	  <None Remove="fonts\msyhbd.ttc" />
	  <None Remove="fonts\msyhl.ttc" />
	  <None Remove="Images\logo.png" />
	  <None Remove="stockdata\cy_stock.db" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="fonts\msyh.ttc">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="fonts\msyhbd.ttc">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="fonts\msyhl.ttc">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Images\logo.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="stockdata\cy_stock.db">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
		<PackageReference Include="ScottPlot.WPF" Version="5.1.59" />
		<PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
	</ItemGroup>

</Project>